name: MacUninstaller
options:
  bundleIdPrefix: io.darevader
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"

targets:
  MacUninstaller:
    type: application
    platform: macOS
    sources:
      - path: MacUninstaller
        excludes:
          - "**/.gitkeep"
          - "**/*.entitlements"
      - path: Shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.r33hab.macuninstall
        INFOPLIST_FILE: MacUninstaller/Info.plist
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        GENERATE_INFOPLIST_FILE: false
        CODE_SIGN_ENTITLEMENTS: MacUninstaller/MacUninstaller.entitlements
        CODE_SIGN_IDENTITY: "Developer ID Application: KRISTOFFER LERSVEEN (4QK74D4L3J)"
        DEVELOPMENT_TEAM: 4QK74D4L3J
        CODE_SIGN_STYLE: Manual
        ENABLE_HARDENED_RUNTIME: true
        SWIFT_OBJC_BRIDGING_HEADER: MacUninstaller/MacUninstaller-Bridging-Header.h
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - target: FinderExtension
        embed: true
    scheme:
      testTargets:
        - MacUninstallerTests

  HelperTool:
    type: tool
    platform: macOS
    sources:
      - path: HelperTool
        excludes:
          - "**/*.plist"
      - path: Shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.r33hab.macuninstall.HelperTool
        INFOPLIST_FILE: HelperTool/Info.plist
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        GENERATE_INFOPLIST_FILE: false

  FinderExtension:
    type: app-extension
    product: com.apple.product-type.finder-sync-extension
    platform: macOS
    sources:
      - path: FinderExtension
        excludes:
          - "**/*.plist"
          - "**/.gitkeep"
      - path: Shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.r33hab.macuninstall.FinderExtension
        PRODUCT_MODULE_NAME: UninstallerFinderExt
        INFOPLIST_FILE: FinderExtension/Info.plist
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        GENERATE_INFOPLIST_FILE: false
        CODE_SIGN_IDENTITY: "Developer ID Application: KRISTOFFER LERSVEEN (4QK74D4L3J)"
        DEVELOPMENT_TEAM: 4QK74D4L3J
        CODE_SIGN_STYLE: Manual
        ENABLE_HARDENED_RUNTIME: true
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/../Frameworks"
          - "@executable_path/../../../../Frameworks"

  MacUninstallerTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: MacUninstallerTests
        excludes:
          - "**/.gitkeep"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.r33hab.macuninstall.Tests
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        GENERATE_INFOPLIST_FILE: true
    dependencies:
      - target: MacUninstaller
